### ISSUE TITLE
Invalid syntax, line 27? Thanks!

### ISSUE THREAD

**Issue by asparaguspee** [sanastasiou/cointracker_importers#2]
File "/Users/[XXXXX]/Downloads/cointracker_importers-master/NexoToCointrackerConverter.py", line 27
    return f"{date.month:02d}/{date.day:02d}/{date.year} {date.hour:02d}:{date.minute:02d}:{date.second:02d}"
                                                                                                            ^
SyntaxError: invalid syntax

**Comment by sanastasiou** [comment]
Hi, which python are you using?

**Comment by asparaguspee** [comment]
Oops! Brand new Mac, still on 2.7.18 — updating now. Thanks!

**Comment by sanastasiou** [comment]
No prob, you'd need version 3.5 or so.

**Comment by sanastasiou** [comment]
Make sure to get the latest version of the script, because Nexo changed a lot of things ( again ) and it's still broken.

For exchanges, the amount bought token is missing.. It will be a placeholder on the converted .csv file which you then have to manually fill in yourself.

**Comment by asparaguspee** [comment]
Wow, what a pain! Thanks for staying on top of it man, you're a hero.

**Comment by sanastasiou** [comment]
No worries :)
